// Permission constants for RISKA HD RBAC system

export const RESOURCES = {
  PATIENT: "patient",
  DOCTOR: "doctor",
  NURSE: "nurse",
  ROOM: "room",
  HD_MACHINE: "hd_machine",
  SHIFT: "shift",
  DIAGNOSIS: "diagnosis",
  MEDICATION: "medication",
  HD_PROTOCOL: "hd_protocol",
  COMPLICATION: "complication",
  USER: "user",
  ROLE: "role",
  AUDIT_LOG: "audit_log",
  NURSE_SCHEDULE: "nurse_schedule",
  PATIENT_SCHEDULE: "patient_schedule",
  RUANG_INFORMASI: "ruang_informasi",
} as const;

export const ACTIONS = {
  CREATE: "create",
  READ: "read",
  UPDATE: "update",
  DELETE: "delete",
  MANAGE: "manage", // Full CRUD access
} as const;

export type Resource = (typeof RESOURCES)[keyof typeof RESOURCES];
export type Action = (typeof ACTIONS)[keyof typeof ACTIONS];

// Permission format: "resource:action"
export const PERMISSIONS = {
  // Patient permissions
  PATIENT_CREATE: `${RESOURCES.PATIENT}:${ACTIONS.CREATE}`,
  PATIENT_READ: `${RESOURCES.PATIENT}:${ACTIONS.READ}`,
  PATIENT_UPDATE: `${RESOURCES.PATIENT}:${ACTIONS.UPDATE}`,
  PATIENT_DELETE: `${RESOURCES.PATIENT}:${ACTIONS.DELETE}`,
  PATIENT_MANAGE: `${RESOURCES.PATIENT}:${ACTIONS.MANAGE}`,

  // Doctor permissions
  DOCTOR_CREATE: `${RESOURCES.DOCTOR}:${ACTIONS.CREATE}`,
  DOCTOR_READ: `${RESOURCES.DOCTOR}:${ACTIONS.READ}`,
  DOCTOR_UPDATE: `${RESOURCES.DOCTOR}:${ACTIONS.UPDATE}`,
  DOCTOR_DELETE: `${RESOURCES.DOCTOR}:${ACTIONS.DELETE}`,
  DOCTOR_MANAGE: `${RESOURCES.DOCTOR}:${ACTIONS.MANAGE}`,

  // Nurse permissions
  NURSE_CREATE: `${RESOURCES.NURSE}:${ACTIONS.CREATE}`,
  NURSE_READ: `${RESOURCES.NURSE}:${ACTIONS.READ}`,
  NURSE_UPDATE: `${RESOURCES.NURSE}:${ACTIONS.UPDATE}`,
  NURSE_DELETE: `${RESOURCES.NURSE}:${ACTIONS.DELETE}`,
  NURSE_MANAGE: `${RESOURCES.NURSE}:${ACTIONS.MANAGE}`,

  // Room permissions
  ROOM_CREATE: `${RESOURCES.ROOM}:${ACTIONS.CREATE}`,
  ROOM_READ: `${RESOURCES.ROOM}:${ACTIONS.READ}`,
  ROOM_UPDATE: `${RESOURCES.ROOM}:${ACTIONS.UPDATE}`,
  ROOM_DELETE: `${RESOURCES.ROOM}:${ACTIONS.DELETE}`,
  ROOM_MANAGE: `${RESOURCES.ROOM}:${ACTIONS.MANAGE}`,

  // HD Machine permissions
  HD_MACHINE_CREATE: `${RESOURCES.HD_MACHINE}:${ACTIONS.CREATE}`,
  HD_MACHINE_READ: `${RESOURCES.HD_MACHINE}:${ACTIONS.READ}`,
  HD_MACHINE_UPDATE: `${RESOURCES.HD_MACHINE}:${ACTIONS.UPDATE}`,
  HD_MACHINE_DELETE: `${RESOURCES.HD_MACHINE}:${ACTIONS.DELETE}`,
  HD_MACHINE_MANAGE: `${RESOURCES.HD_MACHINE}:${ACTIONS.MANAGE}`,

  // Shift permissions
  SHIFT_CREATE: `${RESOURCES.SHIFT}:${ACTIONS.CREATE}`,
  SHIFT_READ: `${RESOURCES.SHIFT}:${ACTIONS.READ}`,
  SHIFT_UPDATE: `${RESOURCES.SHIFT}:${ACTIONS.UPDATE}`,
  SHIFT_DELETE: `${RESOURCES.SHIFT}:${ACTIONS.DELETE}`,
  SHIFT_MANAGE: `${RESOURCES.SHIFT}:${ACTIONS.MANAGE}`,

  // Diagnosis permissions
  DIAGNOSIS_CREATE: `${RESOURCES.DIAGNOSIS}:${ACTIONS.CREATE}`,
  DIAGNOSIS_READ: `${RESOURCES.DIAGNOSIS}:${ACTIONS.READ}`,
  DIAGNOSIS_UPDATE: `${RESOURCES.DIAGNOSIS}:${ACTIONS.UPDATE}`,
  DIAGNOSIS_DELETE: `${RESOURCES.DIAGNOSIS}:${ACTIONS.DELETE}`,
  DIAGNOSIS_MANAGE: `${RESOURCES.DIAGNOSIS}:${ACTIONS.MANAGE}`,

  // Medication permissions
  MEDICATION_CREATE: `${RESOURCES.MEDICATION}:${ACTIONS.CREATE}`,
  MEDICATION_READ: `${RESOURCES.MEDICATION}:${ACTIONS.READ}`,
  MEDICATION_UPDATE: `${RESOURCES.MEDICATION}:${ACTIONS.UPDATE}`,
  MEDICATION_DELETE: `${RESOURCES.MEDICATION}:${ACTIONS.DELETE}`,
  MEDICATION_MANAGE: `${RESOURCES.MEDICATION}:${ACTIONS.MANAGE}`,

  // HD Protocol permissions
  HD_PROTOCOL_CREATE: `${RESOURCES.HD_PROTOCOL}:${ACTIONS.CREATE}`,
  HD_PROTOCOL_READ: `${RESOURCES.HD_PROTOCOL}:${ACTIONS.READ}`,
  HD_PROTOCOL_UPDATE: `${RESOURCES.HD_PROTOCOL}:${ACTIONS.UPDATE}`,
  HD_PROTOCOL_DELETE: `${RESOURCES.HD_PROTOCOL}:${ACTIONS.DELETE}`,
  HD_PROTOCOL_MANAGE: `${RESOURCES.HD_PROTOCOL}:${ACTIONS.MANAGE}`,

  // Complication permissions
  COMPLICATION_CREATE: `${RESOURCES.COMPLICATION}:${ACTIONS.CREATE}`,
  COMPLICATION_READ: `${RESOURCES.COMPLICATION}:${ACTIONS.READ}`,
  COMPLICATION_UPDATE: `${RESOURCES.COMPLICATION}:${ACTIONS.UPDATE}`,
  COMPLICATION_DELETE: `${RESOURCES.COMPLICATION}:${ACTIONS.DELETE}`,
  COMPLICATION_MANAGE: `${RESOURCES.COMPLICATION}:${ACTIONS.MANAGE}`,

  // User management permissions
  USER_CREATE: `${RESOURCES.USER}:${ACTIONS.CREATE}`,
  USER_READ: `${RESOURCES.USER}:${ACTIONS.READ}`,
  USER_UPDATE: `${RESOURCES.USER}:${ACTIONS.UPDATE}`,
  USER_DELETE: `${RESOURCES.USER}:${ACTIONS.DELETE}`,
  USER_MANAGE: `${RESOURCES.USER}:${ACTIONS.MANAGE}`,

  // Role management permissions
  ROLE_CREATE: `${RESOURCES.ROLE}:${ACTIONS.CREATE}`,
  ROLE_READ: `${RESOURCES.ROLE}:${ACTIONS.READ}`,
  ROLE_UPDATE: `${RESOURCES.ROLE}:${ACTIONS.UPDATE}`,
  ROLE_DELETE: `${RESOURCES.ROLE}:${ACTIONS.DELETE}`,
  ROLE_MANAGE: `${RESOURCES.ROLE}:${ACTIONS.MANAGE}`,

  // Audit log permissions
  AUDIT_LOG_READ: `${RESOURCES.AUDIT_LOG}:${ACTIONS.READ}`,

  // Nurse Schedule permissions
  NURSE_SCHEDULE_CREATE: `${RESOURCES.NURSE_SCHEDULE}:${ACTIONS.CREATE}`,
  NURSE_SCHEDULE_READ: `${RESOURCES.NURSE_SCHEDULE}:${ACTIONS.READ}`,
  NURSE_SCHEDULE_UPDATE: `${RESOURCES.NURSE_SCHEDULE}:${ACTIONS.UPDATE}`,
  NURSE_SCHEDULE_DELETE: `${RESOURCES.NURSE_SCHEDULE}:${ACTIONS.DELETE}`,
  NURSE_SCHEDULE_MANAGE: `${RESOURCES.NURSE_SCHEDULE}:${ACTIONS.MANAGE}`,

  // Patient Schedule permissions
  PATIENT_SCHEDULE_CREATE: `${RESOURCES.PATIENT_SCHEDULE}:${ACTIONS.CREATE}`,
  PATIENT_SCHEDULE_READ: `${RESOURCES.PATIENT_SCHEDULE}:${ACTIONS.READ}`,
  PATIENT_SCHEDULE_UPDATE: `${RESOURCES.PATIENT_SCHEDULE}:${ACTIONS.UPDATE}`,
  PATIENT_SCHEDULE_DELETE: `${RESOURCES.PATIENT_SCHEDULE}:${ACTIONS.DELETE}`,
  PATIENT_SCHEDULE_MANAGE: `${RESOURCES.PATIENT_SCHEDULE}:${ACTIONS.MANAGE}`,

  // Ruang Informasi permissions
  RUANG_INFORMASI_CREATE: `${RESOURCES.RUANG_INFORMASI}:${ACTIONS.CREATE}`,
  RUANG_INFORMASI_READ: `${RESOURCES.RUANG_INFORMASI}:${ACTIONS.READ}`,
  RUANG_INFORMASI_UPDATE: `${RESOURCES.RUANG_INFORMASI}:${ACTIONS.UPDATE}`,
  RUANG_INFORMASI_DELETE: `${RESOURCES.RUANG_INFORMASI}:${ACTIONS.DELETE}`,
  RUANG_INFORMASI_MANAGE: `${RESOURCES.RUANG_INFORMASI}:${ACTIONS.MANAGE}`,
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// All permissions as an array
export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
